import { Employee, Department, Position } from './types';

export const DEPARTMENTS: Department[] = [
  { id: 'd1', name: 'Khoa Khám bệnh' },
  { id: 'd2', name: 'Khoa Nội tổng hợp' },
  { id: 'd3', name: 'Khoa Ngoại tổng hợp' },
  { id: 'd4', name: 'Khoa Phụ sản' },
  { id: 'd5', name: 'Khoa Nhi' },
  { id: 'd6', name: 'Phòng Tổ chức - Hành chính' },
  { id: 'd7', name: 'Ban Giám đốc' },
  { id: 'd8', name: 'Khoa Dược' },
];

export const POSITIONS: Position[] = [
  { id: 'p1', name: 'Giám đốc' },
  { id: 'p2', name: 'Phó Giám đốc' },
  { id: 'p3', name: 'Trưởng khoa' },
  { id: 'p4', name: 'Phó khoa' },
  { id: 'p5', name: 'Điều dưỡng trưởng' },
  { id: 'p6', name: 'Bác sĩ' },
  { id: 'p7', name: 'Điều dưỡng' },
  { id: 'p8', name: 'Dược sĩ' },
  { id: 'p9', name: 'Chuyên viên' },
];

export const initialEmployees: Employee[] = [
    {
        id: 'EMP001',
        fullName: 'Nguyễn Văn A',
        dateOfBirth: '1980-05-15',
        gender: 'Nam',
        departmentId: 'd7',
        positionId: 'p1',
        phoneNumber: '0901234567',
        email: 'nguyenvana@email.com',
        isPartyMember: true,
        idCardNumber: '012345678901',
        idCardIssueDate: '2015-10-20',
        employmentType: 'Biên chế sự nghiệp',
        recruitmentDate: '2005-01-10',
        status: 'Đang công tác',
        highestSpecialization: 'CKII Quản lý y tế',
    },
    {
        id: 'EMP002',
        fullName: 'Trần Thị B',
        dateOfBirth: '1985-08-22',
        gender: 'Nữ',
        departmentId: 'd2',
        positionId: 'p3',
        phoneNumber: '0912345678',
        email: 'tranthib@email.com',
        isPartyMember: true,
        idCardNumber: '023456789012',
        idCardIssueDate: '2016-11-25',
        employmentType: 'Biên chế sự nghiệp',
        recruitmentDate: '2010-03-15',
        status: 'Đang công tác',
        highestSpecialization: 'CKI Nội khoa',
    },
    {
        id: 'EMP003',
        fullName: 'Lê Văn C',
        dateOfBirth: '1990-01-30',
        gender: 'Nam',
        departmentId: 'd3',
        positionId: 'p6',
        phoneNumber: '0987654321',
        email: 'levanc@email.com',
        isPartyMember: false,
        idCardNumber: '034567890123',
        idCardIssueDate: '2017-01-05',
        employmentType: 'HĐ trong chỉ tiêu',
        recruitmentDate: '2018-07-01',
        status: 'Đang công tác',
        highestSpecialization: 'ĐH Y khoa',
    },
    {
        id: 'EMP004',
        fullName: 'Phạm Thị D',
        dateOfBirth: '1992-11-12',
        gender: 'Nữ',
        departmentId: 'd2',
        positionId: 'p7',
        phoneNumber: '0911223344',
        email: 'phamthid@email.com',
        isPartyMember: false,
        idCardNumber: '045678901234',
        idCardIssueDate: '2018-02-14',
        employmentType: 'HĐ trong chỉ tiêu',
        recruitmentDate: '2019-09-20',
        status: 'Đang công tác',
        highestSpecialization: 'CĐ Điều dưỡng',
    },
    {
        id: 'EMP005',
        fullName: 'Hoàng Văn E',
        dateOfBirth: '1965-03-20',
        gender: 'Nam',
        departmentId: 'd6',
        positionId: 'p9',
        phoneNumber: '0933445566',
        email: 'hoangvane@email.com',
        isPartyMember: true,
        idCardNumber: '056789012345',
        idCardIssueDate: '2010-06-30',
        employmentType: 'Biên chế sự nghiệp',
        recruitmentDate: '1995-02-01',
        status: 'Đang công tác',
        highestSpecialization: 'ĐH Luật',
    },
    {
        id: 'EMP006',
        fullName: 'Vũ Thị F',
        dateOfBirth: '1995-07-07',
        gender: 'Nữ',
        departmentId: 'd4',
        positionId: 'p6',
        phoneNumber: '0944556677',
        email: 'vuthif@email.com',
        isPartyMember: false,
        idCardNumber: '067890123456',
        idCardIssueDate: '2020-08-19',
        employmentType: 'HĐ trong chỉ tiêu',
        recruitmentDate: '2021-01-15',
        status: 'Đang công tác',
        highestSpecialization: 'ĐH Y khoa',
    },
     {
        id: 'EMP007',
        fullName: 'Đặng Văn G',
        dateOfBirth: '1988-09-18',
        gender: 'Nam',
        departmentId: 'd8',
        positionId: 'p8',
        phoneNumber: '0988776655',
        email: 'dangvang@email.com',
        isPartyMember: false,
        idCardNumber: '078901234567',
        idCardIssueDate: '2019-03-22',
        employmentType: 'Biên chế sự nghiệp',
        recruitmentDate: '2015-06-01',
        status: 'Đang công tác',
        highestSpecialization: 'ĐH Dược',
    },
    {
        id: 'EMP008',
        fullName: 'Bùi Thị H',
        dateOfBirth: '1970-12-01',
        gender: 'Nữ',
        departmentId: 'd3',
        positionId: 'p5',
        phoneNumber: '0977665544',
        email: 'buithih@email.com',
        isPartyMember: true,
        idCardNumber: '089012345678',
        idCardIssueDate: '2011-04-10',
        employmentType: 'Biên chế sự nghiệp',
        recruitmentDate: '2000-08-01',
        status: 'Đang công tác',
        highestSpecialization: 'Cử nhân Điều dưỡng',
    },
    {
        id: 'EMP009',
        fullName: 'Ngô Văn I',
        dateOfBirth: '1964-06-25',
        gender: 'Nam',
        departmentId: 'd1',
        positionId: 'p4',
        phoneNumber: '0966554433',
        email: 'ngovani@email.com',
        isPartyMember: true,
        idCardNumber: '090123456789',
        idCardIssueDate: '2009-09-09',
        employmentType: 'Biên chế sự nghiệp',
        recruitmentDate: '1992-10-10',
        status: 'Đang công tác',
        highestSpecialization: 'CKI Ngoại khoa',
    },
    {
        id: 'EMP010',
        fullName: 'Dương Thị K',
        dateOfBirth: '1998-02-28',
        gender: 'Nữ',
        departmentId: 'd5',
        positionId: 'p7',
        phoneNumber: '0955443322',
        email: 'duongthik@email.com',
        isPartyMember: false,
        idCardNumber: '101234567890',
        idCardIssueDate: '2022-01-20',
        employmentType: 'Hỗ trợ phục vụ',
        recruitmentDate: '2023-03-01',
        status: 'Đang công tác',
        highestSpecialization: 'TC Điều dưỡng',
    }
];